#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define JX_VERSION "0.4.1-portable-win32-posix-emitter"

typedef struct {
    unsigned char *bytes;
    size_t length;
} JxBuffer;

typedef struct {
    const char *input_path;
    const char *output_path;
    const char *asset_path;
    int window_mode;
} JxOptions;

static void jx_die(const char *message) {
    fprintf(stderr, "jx: %s\n", message);
    exit(1);
}

static void jx_die_errno(const char *message) {
    fprintf(stderr, "jx: %s: %s\n", message, strerror(errno));
    exit(1);
}

static void jx_usage(FILE *stream) {
    fprintf(stream,
        "JX %s\n"
        "\n"
        "Usage:\n"
        "  jx emit-c <input.php> -o <output.c>\n"
        "  jx emit-c <input.php> --asset <style.css> -o <output.c>\n"
        "  jx emit-c <input.php> --asset <style.css> --window -o <output.c>\n"
        "  jx compile <input.php> -o <output.c>\n"
        "  jx --version\n"
        "\n"
        "The emitted .c file is GCC-compilable executable code.\n"
        "It contains a Windows/POSIX runtime bridge for the embedded PHP payload.\n",
        JX_VERSION);
}

static const char *jx_basename(const char *path) {
    const char *slash = strrchr(path, '/');
    const char *backslash = strrchr(path, '\\');
    const char *last = slash;
    if (!last || (backslash && backslash > last)) {
        last = backslash;
    }
    return last ? last + 1 : path;
}

static JxBuffer jx_read_file(const char *path) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        jx_die_errno("cannot open input");
    }

    if (fseek(fp, 0, SEEK_END) != 0) {
        fclose(fp);
        jx_die_errno("cannot seek input");
    }

    long size = ftell(fp);
    if (size < 0) {
        fclose(fp);
        jx_die_errno("cannot measure input");
    }

    if (fseek(fp, 0, SEEK_SET) != 0) {
        fclose(fp);
        jx_die_errno("cannot rewind input");
    }

    unsigned char *bytes = NULL;
    if (size > 0) {
        bytes = (unsigned char *)malloc((size_t)size);
        if (!bytes) {
            fclose(fp);
            jx_die("out of memory");
        }

        size_t read_count = fread(bytes, 1, (size_t)size, fp);
        if (read_count != (size_t)size) {
            free(bytes);
            fclose(fp);
            jx_die_errno("cannot read input");
        }
    }

    fclose(fp);

    JxBuffer buffer;
    buffer.bytes = bytes;
    buffer.length = (size_t)size;
    return buffer;
}

static void jx_write_c_string(FILE *out, const char *text) {
    fputc('"', out);
    for (const unsigned char *p = (const unsigned char *)text; *p; ++p) {
        switch (*p) {
            case '\\': fputs("\\\\", out); break;
            case '"': fputs("\\\"", out); break;
            case '\n': fputs("\\n", out); break;
            case '\r': fputs("\\r", out); break;
            case '\t': fputs("\\t", out); break;
            default:
                if (*p < 32 || *p > 126) {
                    fprintf(out, "\\x%02x", *p);
                } else {
                    fputc(*p, out);
                }
        }
    }
    fputc('"', out);
}

static void jx_emit_bytes(FILE *out, const char *symbol, const JxBuffer *input) {
    fprintf(out, "static const unsigned char %s[%zu] = {\n", symbol, input->length == 0 ? 1 : input->length);
    if (input->length == 0) {
        fputs("    0x00\n", out);
    } else {
        for (size_t i = 0; i < input->length; ++i) {
            if (i % 12 == 0) {
                fputs("    ", out);
            }
            fprintf(out, "0x%02x", input->bytes[i]);
            if (i + 1 < input->length) {
                fputs(", ", out);
            }
            if (i % 12 == 11 || i + 1 == input->length) {
                fputc('\n', out);
            }
        }
    }
    fputs("};\n", out);
}

static void jx_emit_runtime(FILE *out, const JxOptions *opt, const JxBuffer *input, const JxBuffer *asset) {
    int has_asset = opt->asset_path != NULL && asset != NULL;

    fputs("/* Generated by JX native Oracle C emitter. */\n", out);
    fputs("#include <errno.h>\n", out);
    fputs("#include <stdio.h>\n", out);
    fputs("#include <stdlib.h>\n", out);
    fputs("#include <string.h>\n", out);
    fputs("#ifdef _WIN32\n", out);
    fputs("#define WIN32_LEAN_AND_MEAN\n", out);
    fputs("#include <windows.h>\n", out);
    fputs("#else\n", out);
    fputs("#include <sys/types.h>\n", out);
    fputs("#include <sys/wait.h>\n", out);
    fputs("#include <unistd.h>\n", out);
    fputs("extern int mkstemp(char *);\n", out);
    fputs("extern int setenv(const char *, const char *, int);\n", out);
    fputs("#endif\n\n", out);

    fputs("static const char *JX_ORACLE_NAME = \"php-payload-exec-oracle\";\n", out);
    fputs("static const char *JX_ORACLE_VERSION = \"0.4.1\";\n", out);
    fputs("static const char *JX_SOURCE_PATH = ", out);
    jx_write_c_string(out, opt->input_path);
    fputs(";\n", out);
    fprintf(out, "static const int jx_window_mode = %d;\n", opt->window_mode ? 1 : 0);
    fprintf(out, "static const size_t jx_php_payload_len = %zu;\n", input->length);
    jx_emit_bytes(out, "jx_php_payload", input);

    fprintf(out, "static const int jx_has_css_asset = %d;\n", has_asset ? 1 : 0);
    fputs("static const char *JX_CSS_ASSET_NAME = ", out);
    jx_write_c_string(out, has_asset ? jx_basename(opt->asset_path) : "");
    fputs(";\n", out);
    fprintf(out, "static const size_t jx_css_asset_len = %zu;\n", has_asset ? asset->length : 0);
    if (has_asset) {
        jx_emit_bytes(out, "jx_css_asset", asset);
    } else {
        JxBuffer empty;
        empty.bytes = NULL;
        empty.length = 0;
        jx_emit_bytes(out, "jx_css_asset", &empty);
    }

    fputs("\nstatic void jx_fail(const char *message) {\n", out);
    fputs("    fprintf(stderr, \"jx generated executable: %s: %s\\n\", message, strerror(errno));\n", out);
    fputs("    exit(1);\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_copy_string(const char *text) {\n", out);
    fputs("    size_t len = strlen(text) + 1;\n", out);
    fputs("    char *copy = (char *)malloc(len);\n", out);
    fputs("    if (!copy) { jx_fail(\"out of memory\"); }\n", out);
    fputs("    memcpy(copy, text, len);\n", out);
    fputs("    return copy;\n", out);
    fputs("}\n\n", out);

    fputs("#ifdef _WIN32\n", out);
    fputs("static char *jx_materialize_bytes(const char *prefix, const unsigned char *bytes, size_t len) {\n", out);
    fputs("    char temp_dir[MAX_PATH];\n", out);
    fputs("    char temp_path[MAX_PATH];\n", out);
    fputs("    if (GetTempPathA((DWORD)sizeof(temp_dir), temp_dir) == 0) { jx_fail(\"cannot get temp path\"); }\n", out);
    fputs("    if (GetTempFileNameA(temp_dir, prefix, 0, temp_path) == 0) { jx_fail(\"cannot create temp file name\"); }\n", out);
    fputs("    HANDLE file = CreateFileA(temp_path, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_TEMPORARY, NULL);\n", out);
    fputs("    if (file == INVALID_HANDLE_VALUE) { jx_fail(\"cannot create temp materialized file\"); }\n", out);
    fputs("    size_t total = 0;\n", out);
    fputs("    while (total < len) {\n", out);
    fputs("        DWORD chunk = (DWORD)((len - total) > 1048576 ? 1048576 : (len - total));\n", out);
    fputs("        DWORD written = 0;\n", out);
    fputs("        if (!WriteFile(file, bytes + total, chunk, &written, NULL) || written == 0) {\n", out);
    fputs("            CloseHandle(file); DeleteFileA(temp_path); jx_fail(\"cannot write temp materialized file\");\n", out);
    fputs("        }\n", out);
    fputs("        total += (size_t)written;\n", out);
    fputs("    }\n", out);
    fputs("    CloseHandle(file);\n", out);
    fputs("    return jx_copy_string(temp_path);\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_quote_arg(const char *arg) {\n", out);
    fputs("    size_t len = strlen(arg);\n", out);
    fputs("    char *out = (char *)malloc(len * 2 + 3);\n", out);
    fputs("    if (!out) { jx_fail(\"out of memory\"); }\n", out);
    fputs("    size_t j = 0; out[j++] = '\"';\n", out);
    fputs("    for (size_t i = 0; i < len; ++i) { if (arg[i] == '\"' || arg[i] == '\\\\') out[j++] = '\\\\'; out[j++] = arg[i]; }\n", out);
    fputs("    out[j++] = '\"'; out[j] = '\\0'; return out;\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_build_command_line(const char *php, const char *payload_path, int argc, char **argv) {\n", out);
    fputs("    size_t cap = 4096; char *cmd = (char *)calloc(1, cap); if (!cmd) { jx_fail(\"out of memory\"); }\n", out);
    fputs("    char *qphp = jx_quote_arg(php); char *qpayload = jx_quote_arg(payload_path);\n", out);
    fputs("    strcat(cmd, qphp); strcat(cmd, \" \" ); strcat(cmd, qpayload); free(qphp); free(qpayload);\n", out);
    fputs("    for (int i = 1; i < argc; ++i) {\n", out);
    fputs("        char *q = jx_quote_arg(argv[i]); size_t need = strlen(cmd) + strlen(q) + 2;\n", out);
    fputs("        if (need > cap) { while (need > cap) cap *= 2; char *next = (char *)realloc(cmd, cap); if (!next) { free(q); free(cmd); jx_fail(\"out of memory\"); } cmd = next; }\n", out);
    fputs("        strcat(cmd, \" \" ); strcat(cmd, q); free(q);\n", out);
    fputs("    }\n", out);
    fputs("    return cmd;\n", out);
    fputs("}\n\n", out);

    fputs("static int jx_exec_php(int argc, char **argv, const char *payload_path, const char *css_path) {\n", out);
    fputs("    const char *php = getenv(\"JX_PHP\"); if (!php || !*php) { php = \"php\"; }\n", out);
    fputs("    if (css_path && jx_has_css_asset) { SetEnvironmentVariableA(\"JX_CSS_FILE\", css_path); SetEnvironmentVariableA(\"JX_CSS_NAME\", JX_CSS_ASSET_NAME); }\n", out);
    fputs("    char *cmd = jx_build_command_line(php, payload_path, argc, argv);\n", out);
    fputs("    STARTUPINFOA si; PROCESS_INFORMATION pi; ZeroMemory(&si, sizeof(si)); ZeroMemory(&pi, sizeof(pi)); si.cb = sizeof(si);\n", out);
    fputs("    BOOL ok = CreateProcessA(NULL, cmd, NULL, NULL, TRUE, 0, NULL, NULL, &si, &pi);\n", out);
    fputs("    free(cmd);\n", out);
    fputs("    if (!ok) { fprintf(stderr, \"jx generated executable: cannot exec PHP runtime '%s': Windows error %lu\\n\", php, (unsigned long)GetLastError()); return 127; }\n", out);
    fputs("    WaitForSingleObject(pi.hProcess, INFINITE); DWORD code = 1; GetExitCodeProcess(pi.hProcess, &code); CloseHandle(pi.hThread); CloseHandle(pi.hProcess); return (int)code;\n", out);
    fputs("}\n", out);
    fputs("#else\n", out);

    fputs("static char *jx_materialize_bytes(const char *prefix, const unsigned char *bytes, size_t len) {\n", out);
    fputs("    char template_path[160];\n", out);
    fputs("    int count = snprintf(template_path, sizeof(template_path), \"/tmp/%s_XXXXXX\", prefix);\n", out);
    fputs("    if (count < 0 || (size_t)count >= sizeof(template_path)) { errno = ENAMETOOLONG; jx_fail(\"cannot create temporary template path\"); }\n", out);
    fputs("    int fd = mkstemp(template_path); if (fd < 0) { jx_fail(\"cannot create temporary materialized file\"); }\n", out);
    fputs("    size_t total = 0; while (total < len) { ssize_t written = write(fd, bytes + total, len - total); if (written <= 0) { close(fd); unlink(template_path); errno = EIO; jx_fail(\"cannot write temp materialized file\"); } total += (size_t)written; }\n", out);
    fputs("    if (close(fd) != 0) { unlink(template_path); jx_fail(\"cannot close materialized file\"); }\n", out);
    fputs("    return jx_copy_string(template_path);\n", out);
    fputs("}\n\n", out);

    fputs("static int jx_exec_php(int argc, char **argv, const char *payload_path, const char *css_path) {\n", out);
    fputs("    const char *php = getenv(\"JX_PHP\"); if (!php || !*php) { php = \"php\"; }\n", out);
    fputs("    if (css_path && jx_has_css_asset) { if (setenv(\"JX_CSS_FILE\", css_path, 1) != 0) { jx_fail(\"cannot export JX_CSS_FILE\"); } if (setenv(\"JX_CSS_NAME\", JX_CSS_ASSET_NAME, 1) != 0) { jx_fail(\"cannot export JX_CSS_NAME\"); } }\n", out);
    fputs("    char **child_argv = (char **)calloc((size_t)argc + 2, sizeof(char *)); if (!child_argv) { jx_fail(\"out of memory\"); }\n", out);
    fputs("    child_argv[0] = (char *)php; child_argv[1] = (char *)payload_path; for (int i = 1; i < argc; ++i) { child_argv[i + 1] = argv[i]; }\n", out);
    fputs("    pid_t pid = fork(); if (pid < 0) { free(child_argv); jx_fail(\"cannot fork PHP runtime\"); }\n", out);
    fputs("    if (pid == 0) { execvp(php, child_argv); fprintf(stderr, \"jx generated executable: cannot exec PHP runtime '%s': %s\\n\", php, strerror(errno)); _exit(127); }\n", out);
    fputs("    free(child_argv); int status = 0; while (waitpid(pid, &status, 0) < 0) { if (errno != EINTR) { jx_fail(\"cannot wait for PHP runtime\"); } }\n", out);
    fputs("    if (WIFEXITED(status)) return WEXITSTATUS(status); if (WIFSIGNALED(status)) return 128 + WTERMSIG(status); return 1;\n", out);
    fputs("}\n", out);
    fputs("#endif\n\n", out);

    fputs("int main(int argc, char **argv) {\n", out);
    fputs("    (void)JX_ORACLE_NAME; (void)JX_ORACLE_VERSION; (void)JX_SOURCE_PATH; (void)jx_window_mode;\n", out);
    fputs("    char *payload_path = jx_materialize_bytes(\"jxphp\", jx_php_payload, jx_php_payload_len);\n", out);
    fputs("    char *css_path = NULL; if (jx_has_css_asset) { css_path = jx_materialize_bytes(\"jxcss\", jx_css_asset, jx_css_asset_len); }\n", out);
    fputs("    int code = jx_exec_php(argc, argv, payload_path, css_path);\n", out);
    fputs("#ifdef _WIN32\n", out);
    fputs("    DeleteFileA(payload_path); if (css_path) DeleteFileA(css_path);\n", out);
    fputs("#else\n", out);
    fputs("    unlink(payload_path); if (css_path) unlink(css_path);\n", out);
    fputs("#endif\n", out);
    fputs("    free(payload_path); if (css_path) free(css_path); return code;\n", out);
    fputs("}\n", out);
}

static void jx_emit_c_file(const JxOptions *opt) {
    JxBuffer input = jx_read_file(opt->input_path);
    JxBuffer asset;
    asset.bytes = NULL;
    asset.length = 0;

    if (opt->asset_path) {
        asset = jx_read_file(opt->asset_path);
    }

    FILE *out = fopen(opt->output_path, "wb");
    if (!out) {
        free(input.bytes);
        free(asset.bytes);
        jx_die_errno("cannot open output");
    }

    jx_emit_runtime(out, opt, &input, opt->asset_path ? &asset : NULL);

    if (fclose(out) != 0) {
        free(input.bytes);
        free(asset.bytes);
        jx_die_errno("cannot close output");
    }

    free(input.bytes);
    free(asset.bytes);
}

static JxOptions jx_parse_options(int argc, char **argv) {
    JxOptions opt;
    opt.input_path = NULL;
    opt.output_path = NULL;
    opt.asset_path = NULL;
    opt.window_mode = 0;

    if (argc < 3) {
        jx_usage(stderr);
        exit(1);
    }

    opt.input_path = argv[2];
    for (int i = 3; i < argc; ++i) {
        if (strcmp(argv[i], "-o") == 0) {
            if (i + 1 >= argc) { jx_usage(stderr); exit(1); }
            opt.output_path = argv[++i];
        } else if (strcmp(argv[i], "--asset") == 0) {
            if (i + 1 >= argc) { jx_usage(stderr); exit(1); }
            opt.asset_path = argv[++i];
        } else if (strcmp(argv[i], "--window") == 0 || strcmp(argv[i], "--window=browser") == 0) {
            opt.window_mode = 1;
        } else {
            jx_usage(stderr);
            exit(1);
        }
    }

    if (!opt.output_path) {
        jx_usage(stderr);
        exit(1);
    }

    return opt;
}

int main(int argc, char **argv) {
    if (argc == 2 && strcmp(argv[1], "--version") == 0) {
        printf("JX %s\n", JX_VERSION);
        return 0;
    }

    if (argc < 2 || strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
        jx_usage(argc < 2 ? stderr : stdout);
        return argc < 2 ? 1 : 0;
    }

    const char *command = argv[1];
    if (strcmp(command, "emit-c") != 0 && strcmp(command, "compile") != 0) {
        jx_usage(stderr);
        return 1;
    }

    JxOptions opt = jx_parse_options(argc, argv);
    jx_emit_c_file(&opt);
    printf("JX emitted GCC-compilable C: %s -> %s\n", opt.input_path, opt.output_path);
    return 0;
}
