#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

extern int mkstemp(char *);
extern int setenv(const char *, const char *, int);

#define JX_VERSION "0.4.0-native-window-emitter"

typedef struct {
    unsigned char *bytes;
    size_t length;
} JxBuffer;

typedef struct {
    const char *input_path;
    const char *asset_path;
    const char *output_path;
    int window_mode;
} JxEmitOptions;

static void jx_die(const char *message) {
    fprintf(stderr, "jx: %s\n", message);
    exit(1);
}

static void jx_die_errno(const char *message) {
    fprintf(stderr, "jx: %s: %s\n", message, strerror(errno));
    exit(1);
}

static void jx_usage(FILE *stream) {
    fprintf(stream,
        "JX %s\n"
        "\n"
        "Usage:\n"
        "  jx emit-c <input.php> -o <output.c>\n"
        "  jx emit-c <input.php> --asset <style.css> -o <output.c>\n"
        "  jx emit-c <input.php> --asset <style.css> --window -o <output.c>\n"
        "  jx compile <input.php> -o <output.c>\n"
        "  jx compile <input.php> --asset <style.css> -o <output.c>\n"
        "  jx compile <input.php> --asset <style.css> --window -o <output.c>\n"
        "  jx --version\n"
        "\n"
        "The emitted .c file is GCC-compilable executable code.\n"
        "It contains the PHP source payload plus the JX Oracle runtime bridge.\n"
        "Optional CSS assets are embedded and exposed as JX_CSS_FILE and JX_CSS_NAME.\n"
        "Window mode captures rendered HTML and opens it in a local window/browser.\n",
        JX_VERSION);
}

static const char *jx_basename(const char *path) {
    const char *slash = strrchr(path, '/');
    if (slash) {
        return slash + 1;
    }
    return path;
}

static JxBuffer jx_read_file(const char *path) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        jx_die_errno("cannot open input");
    }

    if (fseek(fp, 0, SEEK_END) != 0) {
        fclose(fp);
        jx_die_errno("cannot seek input");
    }

    long size = ftell(fp);
    if (size < 0) {
        fclose(fp);
        jx_die_errno("cannot measure input");
    }

    if (fseek(fp, 0, SEEK_SET) != 0) {
        fclose(fp);
        jx_die_errno("cannot rewind input");
    }

    unsigned char *bytes = NULL;
    if (size > 0) {
        bytes = (unsigned char *)malloc((size_t)size);
        if (!bytes) {
            fclose(fp);
            jx_die("out of memory");
        }

        size_t read_count = fread(bytes, 1, (size_t)size, fp);
        if (read_count != (size_t)size) {
            free(bytes);
            fclose(fp);
            jx_die_errno("cannot read input");
        }
    }

    fclose(fp);

    JxBuffer buffer;
    buffer.bytes = bytes;
    buffer.length = (size_t)size;
    return buffer;
}

static void jx_write_c_string(FILE *out, const char *text) {
    fputc('"', out);
    for (const unsigned char *p = (const unsigned char *)text; *p; ++p) {
        switch (*p) {
            case '\\': fputs("\\\\", out); break;
            case '"': fputs("\\\"", out); break;
            case '\n': fputs("\\n", out); break;
            case '\r': fputs("\\r", out); break;
            case '\t': fputs("\\t", out); break;
            default:
                if (*p < 32 || *p > 126) {
                    fprintf(out, "\\x%02x", *p);
                } else {
                    fputc(*p, out);
                }
        }
    }
    fputc('"', out);
}

static void jx_emit_bytes(FILE *out, const char *symbol, const JxBuffer *input) {
    fprintf(out, "static const unsigned char %s[%zu] = {\n", symbol, input->length == 0 ? 1 : input->length);
    if (input->length == 0) {
        fputs("    0x00\n", out);
    } else {
        for (size_t i = 0; i < input->length; ++i) {
            if (i % 12 == 0) {
                fputs("    ", out);
            }
            fprintf(out, "0x%02x", input->bytes[i]);
            if (i + 1 < input->length) {
                fputs(", ", out);
            }
            if (i % 12 == 11 || i + 1 == input->length) {
                fputc('\n', out);
            }
        }
    }
    fputs("};\n", out);
}

static void jx_emit_runtime(
    FILE *out,
    const char *source_path,
    const JxBuffer *input,
    const char *asset_path,
    const JxBuffer *asset,
    int window_mode
) {
    int has_asset = asset_path != NULL && asset != NULL;

    fputs("/*\n", out);
    fputs(" * Generated by JX native Oracle C emitter.\n", out);
    fputs(" * This file is standalone C source. Compile it with gcc/cc.\n", out);
    fputs(" * It embeds the PHP payload, optional CSS, and a window/browser launcher.\n", out);
    fputs(" */\n", out);
    fputs("#include <errno.h>\n", out);
    fputs("#include <fcntl.h>\n", out);
    fputs("#include <stdio.h>\n", out);
    fputs("#include <stdlib.h>\n", out);
    fputs("#include <string.h>\n", out);
    fputs("#include <sys/stat.h>\n", out);
    fputs("#include <sys/types.h>\n", out);
    fputs("#include <sys/wait.h>\n", out);
    fputs("#include <unistd.h>\n\n", out);
    fputs("extern int mkstemp(char *);\n", out);
    fputs("extern int setenv(const char *, const char *, int);\n\n", out);

    fputs("static const char *JX_ORACLE_NAME = \"php-payload-window-oracle\";\n", out);
    fputs("static const char *JX_ORACLE_VERSION = \"0.4.0\";\n", out);
    fputs("static const char *JX_SOURCE_PATH = ", out);
    jx_write_c_string(out, source_path);
    fputs(";\n", out);
    fprintf(out, "static const int jx_window_mode = %d;\n", window_mode ? 1 : 0);
    fprintf(out, "static const size_t jx_php_payload_len = %zu;\n", input->length);
    jx_emit_bytes(out, "jx_php_payload", input);

    fprintf(out, "static const int jx_has_css_asset = %d;\n", has_asset ? 1 : 0);
    fputs("static const char *JX_CSS_ASSET_NAME = ", out);
    jx_write_c_string(out, has_asset ? jx_basename(asset_path) : "");
    fputs(";\n", out);
    fprintf(out, "static const size_t jx_css_asset_len = %zu;\n", has_asset ? asset->length : 0);
    if (has_asset) {
        jx_emit_bytes(out, "jx_css_asset", asset);
    } else {
        JxBuffer empty;
        empty.bytes = NULL;
        empty.length = 0;
        jx_emit_bytes(out, "jx_css_asset", &empty);
    }

    fputs("\n", out);
    fputs("static void jx_oracle_fail(const char *message) {\n", out);
    fputs("    fprintf(stderr, \"jx generated executable: %s: %s\\n\", message, strerror(errno));\n", out);
    fputs("    exit(1);\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_oracle_copy_path(const char *path) {\n", out);
    fputs("    size_t len = strlen(path) + 1;\n", out);
    fputs("    char *copy = (char *)malloc(len);\n", out);
    fputs("    if (!copy) { jx_oracle_fail(\"cannot allocate temporary path\"); }\n", out);
    fputs("    memcpy(copy, path, len);\n", out);
    fputs("    return copy;\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_oracle_materialize_bytes(const char *prefix, const unsigned char *bytes, size_t len) {\n", out);
    fputs("    char template_path[128];\n", out);
    fputs("    int count = snprintf(template_path, sizeof(template_path), \"/tmp/%s_XXXXXX\", prefix);\n", out);
    fputs("    if (count < 0 || (size_t)count >= sizeof(template_path)) { errno = ENAMETOOLONG; jx_oracle_fail(\"cannot create temporary template path\"); }\n", out);
    fputs("    int fd = mkstemp(template_path);\n", out);
    fputs("    if (fd < 0) { jx_oracle_fail(\"cannot create temporary materialized file\"); }\n", out);
    fputs("    size_t written_total = 0;\n", out);
    fputs("    while (written_total < len) {\n", out);
    fputs("        ssize_t written = write(fd, bytes + written_total, len - written_total);\n", out);
    fputs("        if (written < 0) { close(fd); unlink(template_path); jx_oracle_fail(\"cannot write materialized file\"); }\n", out);
    fputs("        if (written == 0) { close(fd); unlink(template_path); errno = EIO; jx_oracle_fail(\"short write on materialized file\"); }\n", out);
    fputs("        written_total += (size_t)written;\n", out);
    fputs("    }\n", out);
    fputs("    if (close(fd) != 0) { unlink(template_path); jx_oracle_fail(\"cannot close materialized file\"); }\n", out);
    fputs("    return jx_oracle_copy_path(template_path);\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_oracle_make_empty_temp(const char *prefix) {\n", out);
    fputs("    char template_path[128];\n", out);
    fputs("    int count = snprintf(template_path, sizeof(template_path), \"/tmp/%s_XXXXXX.html\", prefix);\n", out);
    fputs("    if (count < 0 || (size_t)count >= sizeof(template_path)) { errno = ENAMETOOLONG; jx_oracle_fail(\"cannot create temporary html path\"); }\n", out);
    fputs("    char *path = jx_oracle_copy_path(template_path);\n", out);
    fputs("    int fd = mkstemp(path);\n", out);
    fputs("    if (fd < 0) { free(path); jx_oracle_fail(\"cannot create temporary html file\"); }\n", out);
    fputs("    close(fd);\n", out);
    fputs("    return path;\n", out);
    fputs("}\n\n", out);

    fputs("static int jx_wait_for(pid_t pid) {\n", out);
    fputs("    int status = 0;\n", out);
    fputs("    while (waitpid(pid, &status, 0) < 0) { if (errno != EINTR) { jx_oracle_fail(\"cannot wait for child process\"); } }\n", out);
    fputs("    if (WIFEXITED(status)) { return WEXITSTATUS(status); }\n", out);
    fputs("    if (WIFSIGNALED(status)) { return 128 + WTERMSIG(status); }\n", out);
    fputs("    return 1;\n", out);
    fputs("}\n\n", out);

    fputs("static int jx_oracle_exec_php(int argc, char **argv, const char *payload_path, const char *css_path, const char *html_path) {\n", out);
    fputs("    const char *php = getenv(\"JX_PHP\");\n", out);
    fputs("    if (!php || !*php) { php = \"php\"; }\n", out);
    fputs("    if (css_path && jx_has_css_asset) {\n", out);
    fputs("        if (setenv(\"JX_CSS_FILE\", css_path, 1) != 0) { jx_oracle_fail(\"cannot export JX_CSS_FILE\"); }\n", out);
    fputs("        if (setenv(\"JX_CSS_NAME\", JX_CSS_ASSET_NAME, 1) != 0) { jx_oracle_fail(\"cannot export JX_CSS_NAME\"); }\n", out);
    fputs("    }\n", out);
    fputs("    char **child_argv = (char **)calloc((size_t)argc + 2, sizeof(char *));\n", out);
    fputs("    if (!child_argv) { jx_oracle_fail(\"cannot allocate child argv\"); }\n", out);
    fputs("    child_argv[0] = (char *)php;\n", out);
    fputs("    child_argv[1] = (char *)payload_path;\n", out);
    fputs("    for (int i = 1; i < argc; ++i) { child_argv[i + 1] = argv[i]; }\n", out);
    fputs("    pid_t pid = fork();\n", out);
    fputs("    if (pid < 0) { free(child_argv); jx_oracle_fail(\"cannot fork PHP runtime\"); }\n", out);
    fputs("    if (pid == 0) {\n", out);
    fputs("        if (html_path) {\n", out);
    fputs("            int html_fd = open(html_path, O_WRONLY | O_TRUNC);\n", out);
    fputs("            if (html_fd < 0) { _exit(126); }\n", out);
    fputs("            if (dup2(html_fd, STDOUT_FILENO) < 0) { _exit(126); }\n", out);
    fputs("            close(html_fd);\n", out);
    fputs("        }\n", out);
    fputs("        execvp(php, child_argv);\n", out);
    fputs("        fprintf(stderr, \"jx generated executable: cannot exec PHP runtime '%s': %s\\n\", php, strerror(errno));\n", out);
    fputs("        _exit(127);\n", out);
    fputs("    }\n", out);
    fputs("    free(child_argv);\n", out);
    fputs("    return jx_wait_for(pid);\n", out);
    fputs("}\n\n", out);

    fputs("static int jx_try_open_with(const char *program, const char *a, const char *b, const char *path) {\n", out);
    fputs("    pid_t pid = fork();\n", out);
    fputs("    if (pid < 0) { return 1; }\n", out);
    fputs("    if (pid == 0) {\n", out);
    fputs("        if (a && b) { execlp(program, program, a, b, path, (char *)NULL); }\n", out);
    fputs("        else if (a) { execlp(program, program, a, path, (char *)NULL); }\n", out);
    fputs("        else { execlp(program, program, path, (char *)NULL); }\n", out);
    fputs("        _exit(127);\n", out);
    fputs("    }\n", out);
    fputs("    return jx_wait_for(pid);\n", out);
    fputs("}\n\n", out);

    fputs("static void jx_oracle_open_window(const char *html_path) {\n", out);
    fputs("    printf(\"JX_WINDOW_FILE=%s\\n\", html_path);\n", out);
    fputs("    if (getenv(\"JX_NO_OPEN\")) { return; }\n", out);
    fputs("    const char *custom = getenv(\"JX_OPEN\");\n", out);
    fputs("    if (custom && *custom && jx_try_open_with(custom, NULL, NULL, html_path) == 0) { return; }\n", out);
    fputs("    if (jx_try_open_with(\"xdg-open\", NULL, NULL, html_path) == 0) { return; }\n", out);
    fputs("    if (jx_try_open_with(\"wslview\", NULL, NULL, html_path) == 0) { return; }\n", out);
    fputs("    if (jx_try_open_with(\"open\", NULL, NULL, html_path) == 0) { return; }\n", out);
    fputs("    (void)jx_try_open_with(\"cmd.exe\", \"/C\", \"start\", html_path);\n", out);
    fputs("}\n\n", out);

    fputs("int main(int argc, char **argv) {\n", out);
    fputs("    (void)JX_ORACLE_NAME; (void)JX_ORACLE_VERSION; (void)JX_SOURCE_PATH;\n", out);
    fputs("    char *payload_path = jx_oracle_materialize_bytes(\"jx_php_payload\", jx_php_payload, jx_php_payload_len);\n", out);
    fputs("    char *css_path = NULL;\n", out);
    fputs("    if (jx_has_css_asset) { css_path = jx_oracle_materialize_bytes(\"jx_css_asset\", jx_css_asset, jx_css_asset_len); }\n", out);
    fputs("    char *html_path = NULL;\n", out);
    fputs("    if (jx_window_mode) { html_path = jx_oracle_make_empty_temp(\"jx_window\"); }\n", out);
    fputs("    int code = jx_oracle_exec_php(argc, argv, payload_path, css_path, html_path);\n", out);
    fputs("    unlink(payload_path); free(payload_path);\n", out);
    fputs("    if (css_path) { unlink(css_path); free(css_path); }\n", out);
    fputs("    if (code == 0 && jx_window_mode && html_path) { jx_oracle_open_window(html_path); }\n", out);
    fputs("    if (html_path) { free(html_path); }\n", out);
    fputs("    return code;\n", out);
    fputs("}\n", out);
}

static void jx_emit_c_file(const JxEmitOptions *options) {
    JxBuffer input = jx_read_file(options->input_path);
    JxBuffer asset;
    asset.bytes = NULL;
    asset.length = 0;

    if (options->asset_path) {
        asset = jx_read_file(options->asset_path);
    }

    FILE *out = fopen(options->output_path, "wb");
    if (!out) {
        free(input.bytes);
        free(asset.bytes);
        jx_die_errno("cannot open output");
    }

    jx_emit_runtime(out, options->input_path, &input, options->asset_path, options->asset_path ? &asset : NULL, options->window_mode);

    if (fclose(out) != 0) {
        free(input.bytes);
        free(asset.bytes);
        jx_die_errno("cannot close output");
    }

    free(input.bytes);
    free(asset.bytes);
}

static int jx_parse_emit_options(int argc, char **argv, JxEmitOptions *options) {
    if (argc < 5) {
        return 0;
    }

    options->input_path = argv[2];
    options->asset_path = NULL;
    options->output_path = NULL;
    options->window_mode = 0;

    for (int i = 3; i < argc; ++i) {
        if (strcmp(argv[i], "--asset") == 0) {
            if (i + 1 >= argc) { return 0; }
            options->asset_path = argv[++i];
        } else if (strcmp(argv[i], "--window") == 0) {
            options->window_mode = 1;
        } else if (strcmp(argv[i], "-o") == 0) {
            if (i + 1 >= argc) { return 0; }
            options->output_path = argv[++i];
        } else {
            return 0;
        }
    }

    return options->input_path != NULL && options->output_path != NULL;
}

int main(int argc, char **argv) {
    if (argc == 2 && strcmp(argv[1], "--version") == 0) {
        printf("JX %s\n", JX_VERSION);
        return 0;
    }

    if (argc < 2 || strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
        jx_usage(argc < 2 ? stderr : stdout);
        return argc < 2 ? 1 : 0;
    }

    const char *command = argv[1];
    if (strcmp(command, "emit-c") != 0 && strcmp(command, "compile") != 0) {
        jx_usage(stderr);
        return 1;
    }

    JxEmitOptions options;
    if (!jx_parse_emit_options(argc, argv, &options)) {
        jx_usage(stderr);
        return 1;
    }

    jx_emit_c_file(&options);
    printf("JX emitted GCC-compilable C: %s -> %s", options.input_path, options.output_path);
    if (options.asset_path) {
        printf(" with asset %s", options.asset_path);
    }
    if (options.window_mode) {
        printf(" in window mode");
    }
    printf("\n");
    return 0;
}
