#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#define JX_VERSION "0.2.0-native-oracle-c-emitter"

typedef struct {
    unsigned char *bytes;
    size_t length;
} JxBuffer;

static void jx_die(const char *message) {
    fprintf(stderr, "jx: %s\n", message);
    exit(1);
}

static void jx_die_errno(const char *message) {
    fprintf(stderr, "jx: %s: %s\n", message, strerror(errno));
    exit(1);
}

static void jx_usage(FILE *stream) {
    fprintf(stream,
        "JX %s\n"
        "\n"
        "Usage:\n"
        "  jx emit-c <input.php> -o <output.c>\n"
        "  jx compile <input.php> -o <output.c>\n"
        "  jx --version\n"
        "\n"
        "The emitted .c file is GCC-compilable executable code.\n"
        "It contains the PHP source payload plus the JX Oracle runtime bridge.\n",
        JX_VERSION);
}

static JxBuffer jx_read_file(const char *path) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        jx_die_errno("cannot open input");
    }

    if (fseek(fp, 0, SEEK_END) != 0) {
        fclose(fp);
        jx_die_errno("cannot seek input");
    }

    long size = ftell(fp);
    if (size < 0) {
        fclose(fp);
        jx_die_errno("cannot measure input");
    }

    if (fseek(fp, 0, SEEK_SET) != 0) {
        fclose(fp);
        jx_die_errno("cannot rewind input");
    }

    unsigned char *bytes = NULL;
    if (size > 0) {
        bytes = (unsigned char *)malloc((size_t)size);
        if (!bytes) {
            fclose(fp);
            jx_die("out of memory");
        }

        size_t read_count = fread(bytes, 1, (size_t)size, fp);
        if (read_count != (size_t)size) {
            free(bytes);
            fclose(fp);
            jx_die_errno("cannot read input");
        }
    }

    fclose(fp);

    JxBuffer buffer;
    buffer.bytes = bytes;
    buffer.length = (size_t)size;
    return buffer;
}

static void jx_write_c_string(FILE *out, const char *text) {
    fputc('"', out);
    for (const unsigned char *p = (const unsigned char *)text; *p; ++p) {
        switch (*p) {
            case '\\': fputs("\\\\", out); break;
            case '"': fputs("\\\"", out); break;
            case '\n': fputs("\\n", out); break;
            case '\r': fputs("\\r", out); break;
            case '\t': fputs("\\t", out); break;
            default:
                if (*p < 32 || *p > 126) {
                    fprintf(out, "\\x%02x", *p);
                } else {
                    fputc(*p, out);
                }
        }
    }
    fputc('"', out);
}

static void jx_emit_php_bytes(FILE *out, const JxBuffer *input) {
    fprintf(out, "static const unsigned char jx_php_payload[%zu] = {\n", input->length == 0 ? 1 : input->length);
    if (input->length == 0) {
        fputs("    0x00\n", out);
    } else {
        for (size_t i = 0; i < input->length; ++i) {
            if (i % 12 == 0) {
                fputs("    ", out);
            }
            fprintf(out, "0x%02x", input->bytes[i]);
            if (i + 1 < input->length) {
                fputs(", ", out);
            }
            if (i % 12 == 11 || i + 1 == input->length) {
                fputc('\n', out);
            }
        }
    }
    fputs("};\n", out);
}

static void jx_emit_runtime(FILE *out, const char *source_path, const JxBuffer *input) {
    fputs("/*\n", out);
    fputs(" * Generated by JX native Oracle C emitter.\n", out);
    fputs(" * This file is standalone C source. Compile it with gcc/cc.\n", out);
    fputs(" * It embeds the original PHP payload and executes it through the local PHP runtime.\n", out);
    fputs(" */\n", out);
    fputs("#include <errno.h>\n", out);
    fputs("#include <fcntl.h>\n", out);
    fputs("#include <stdio.h>\n", out);
    fputs("#include <stdlib.h>\n", out);
    fputs("#include <string.h>\n", out);
    fputs("#include <sys/stat.h>\n", out);
    fputs("#include <sys/types.h>\n", out);
    fputs("#include <sys/wait.h>\n", out);
    fputs("#include <unistd.h>\n\n", out);

    fputs("static const char *JX_ORACLE_NAME = \"php-payload-exec-oracle\";\n", out);
    fputs("static const char *JX_ORACLE_VERSION = \"0.2.0\";\n", out);
    fputs("static const char *JX_ORACLE_CAPABILITY = \"embedded PHP payload to executable process\";\n", out);
    fputs("static const char *JX_SOURCE_PATH = ", out);
    jx_write_c_string(out, source_path);
    fputs(";\n", out);
    fprintf(out, "static const size_t jx_php_payload_len = %zu;\n", input->length);
    jx_emit_php_bytes(out, input);

    fputs("\n", out);
    fputs("static void jx_oracle_fail(const char *message) {\n", out);
    fputs("    fprintf(stderr, \"jx generated executable: %s: %s\\n\", message, strerror(errno));\n", out);
    fputs("    exit(1);\n", out);
    fputs("}\n\n", out);

    fputs("static char *jx_oracle_materialize_payload(void) {\n", out);
    fputs("    char template_path[] = \"/tmp/jx_php_payload_XXXXXX.php\";\n", out);
    fputs("    int fd = mkstemps(template_path, 4);\n", out);
    fputs("    if (fd < 0) {\n", out);
    fputs("        jx_oracle_fail(\"cannot create temporary PHP payload\");\n", out);
    fputs("    }\n", out);
    fputs("    size_t written_total = 0;\n", out);
    fputs("    while (written_total < jx_php_payload_len) {\n", out);
    fputs("        ssize_t written = write(fd, jx_php_payload + written_total, jx_php_payload_len - written_total);\n", out);
    fputs("        if (written < 0) {\n", out);
    fputs("            close(fd);\n", out);
    fputs("            unlink(template_path);\n", out);
    fputs("            jx_oracle_fail(\"cannot write temporary PHP payload\");\n", out);
    fputs("        }\n", out);
    fputs("        written_total += (size_t)written;\n", out);
    fputs("    }\n", out);
    fputs("    if (close(fd) != 0) {\n", out);
    fputs("        unlink(template_path);\n", out);
    fputs("        jx_oracle_fail(\"cannot close temporary PHP payload\");\n", out);
    fputs("    }\n", out);
    fputs("    char *copy = strdup(template_path);\n", out);
    fputs("    if (!copy) {\n", out);
    fputs("        unlink(template_path);\n", out);
    fputs("        jx_oracle_fail(\"cannot copy temporary PHP path\");\n", out);
    fputs("    }\n", out);
    fputs("    return copy;\n", out);
    fputs("}\n\n", out);

    fputs("static int jx_oracle_exec_php(int argc, char **argv, const char *payload_path) {\n", out);
    fputs("    const char *php = getenv(\"JX_PHP\");\n", out);
    fputs("    if (!php || !*php) {\n", out);
    fputs("        php = \"php\";\n", out);
    fputs("    }\n", out);
    fputs("    char **child_argv = (char **)calloc((size_t)argc + 2, sizeof(char *));\n", out);
    fputs("    if (!child_argv) {\n", out);
    fputs("        jx_oracle_fail(\"cannot allocate child argv\");\n", out);
    fputs("    }\n", out);
    fputs("    child_argv[0] = (char *)php;\n", out);
    fputs("    child_argv[1] = (char *)payload_path;\n", out);
    fputs("    for (int i = 1; i < argc; ++i) {\n", out);
    fputs("        child_argv[i + 1] = argv[i];\n", out);
    fputs("    }\n", out);
    fputs("    pid_t pid = fork();\n", out);
    fputs("    if (pid < 0) {\n", out);
    fputs("        free(child_argv);\n", out);
    fputs("        jx_oracle_fail(\"cannot fork PHP runtime\");\n", out);
    fputs("    }\n", out);
    fputs("    if (pid == 0) {\n", out);
    fputs("        execvp(php, child_argv);\n", out);
    fputs("        fprintf(stderr, \"jx generated executable: cannot exec PHP runtime '%s': %s\\n\", php, strerror(errno));\n", out);
    fputs("        _exit(127);\n", out);
    fputs("    }\n", out);
    fputs("    free(child_argv);\n", out);
    fputs("    int status = 0;\n", out);
    fputs("    while (waitpid(pid, &status, 0) < 0) {\n", out);
    fputs("        if (errno != EINTR) {\n", out);
    fputs("            jx_oracle_fail(\"cannot wait for PHP runtime\");\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    if (WIFEXITED(status)) {\n", out);
    fputs("        return WEXITSTATUS(status);\n", out);
    fputs("    }\n", out);
    fputs("    if (WIFSIGNALED(status)) {\n", out);
    fputs("        return 128 + WTERMSIG(status);\n", out);
    fputs("    }\n", out);
    fputs("    return 1;\n", out);
    fputs("}\n\n", out);

    fputs("int main(int argc, char **argv) {\n", out);
    fputs("    (void)JX_ORACLE_NAME;\n", out);
    fputs("    (void)JX_ORACLE_VERSION;\n", out);
    fputs("    (void)JX_ORACLE_CAPABILITY;\n", out);
    fputs("    (void)JX_SOURCE_PATH;\n", out);
    fputs("    char *payload_path = jx_oracle_materialize_payload();\n", out);
    fputs("    int code = jx_oracle_exec_php(argc, argv, payload_path);\n", out);
    fputs("    unlink(payload_path);\n", out);
    fputs("    free(payload_path);\n", out);
    fputs("    return code;\n", out);
    fputs("}\n", out);
}

static void jx_emit_c_file(const char *input_path, const char *output_path) {
    JxBuffer input = jx_read_file(input_path);

    FILE *out = fopen(output_path, "wb");
    if (!out) {
        free(input.bytes);
        jx_die_errno("cannot open output");
    }

    jx_emit_runtime(out, input_path, &input);

    if (fclose(out) != 0) {
        free(input.bytes);
        jx_die_errno("cannot close output");
    }

    free(input.bytes);
}

int main(int argc, char **argv) {
    if (argc == 2 && strcmp(argv[1], "--version") == 0) {
        printf("JX %s\n", JX_VERSION);
        return 0;
    }

    if (argc < 2 || strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
        jx_usage(argc < 2 ? stderr : stdout);
        return argc < 2 ? 1 : 0;
    }

    const char *command = argv[1];
    if (strcmp(command, "emit-c") != 0 && strcmp(command, "compile") != 0) {
        jx_usage(stderr);
        return 1;
    }

    if (argc != 5 || strcmp(argv[3], "-o") != 0) {
        jx_usage(stderr);
        return 1;
    }

    const char *input_path = argv[2];
    const char *output_path = argv[4];
    jx_emit_c_file(input_path, output_path);
    printf("JX emitted GCC-compilable C: %s -> %s\n", input_path, output_path);
    return 0;
}
