<?php
namespace Jx;

final class JxCompiler
{
    private string $root;

    public function __construct(string $root)
    {
        $this->root = $root;
    }

    public function main(array $argv): int
    {
        $command = $argv[1] ?? 'help';

        return match ($command) {
            'compile' => $this->compileCommand(array_slice($argv, 2)),
            'run' => $this->runCommand(array_slice($argv, 2)),
            'help', '--help', '-h' => $this->help(),
            default => $this->fail("unknown command: {$command}\n"),
        };
    }

    private function compileCommand(array $args): int
    {
        [$input, $output] = $this->parseCompileArgs($args);

        if ($input === null || $output === null) {
            return $this->fail("usage: ./jx compile input.php -o build/app\n");
        }

        try {
            $this->compile($input, $output);
        } catch (\Throwable $e) {
            return $this->fail($e->getMessage() . "\n");
        }

        fwrite(STDOUT, "compiled {$input} -> {$output}\n");
        return 0;
    }

    private function runCommand(array $args): int
    {
        $separator = array_search('--', $args, true);
        $programArgs = [];

        if ($separator !== false) {
            $programArgs = array_slice($args, $separator + 1);
            $args = array_slice($args, 0, $separator);
        }

        $input = $args[0] ?? null;
        if ($input === null) {
            return $this->fail("usage: ./jx run input.php -- arg1 arg2\n");
        }

        $tmp = sys_get_temp_dir() . '/jx-' . bin2hex(random_bytes(8));

        try {
            $this->compile($input, $tmp);
            return $this->exec(array_merge([$tmp], $programArgs));
        } catch (\Throwable $e) {
            return $this->fail($e->getMessage() . "\n");
        } finally {
            if (is_file($tmp)) {
                @unlink($tmp);
            }
        }
    }

    public function compile(string $input, string $output): void
    {
        if (!is_file($input)) {
            throw new \RuntimeException("input file not found: {$input}");
        }

        $source = file_get_contents($input);
        if ($source === false) {
            throw new \RuntimeException("could not read input file: {$input}");
        }

        $this->assertPhpSource($source, $input);

        $dir = dirname($output);
        if ($dir !== '' && $dir !== '.' && !is_dir($dir) && !mkdir($dir, 0775, true)) {
            throw new \RuntimeException("could not create output directory: {$dir}");
        }

        $artifact = $this->artifact($source, basename($input));
        if (file_put_contents($output, $artifact) === false) {
            throw new \RuntimeException("could not write output file: {$output}");
        }

        @chmod($output, 0755);
    }

    private function artifact(string $source, string $sourceName): string
    {
        $payload = base64_encode($source);
        $name = addslashes($sourceName);

        return <<<PHP
#!/usr/bin/env php
<?php
// Generated by JX. This first executable-code layer embeds PHP source and
// delegates execution to the installed PHP runtime while JX grows native lowering.
\$jxPayload = '{$payload}';
\$jxSourceName = '{$name}';
\$jxPhp = getenv('JX_PHP') ?: PHP_BINARY;
\$jxTmp = tempnam(sys_get_temp_dir(), 'jx-src-');
if (\$jxTmp === false) {
    fwrite(STDERR, "JX: could not allocate temp source\n");
    exit(125);
}
\$jxSourcePath = \$jxTmp . '.php';
@unlink(\$jxTmp);
if (file_put_contents(\$jxSourcePath, base64_decode(\$jxPayload, true)) === false) {
    fwrite(STDERR, "JX: could not write temp source\n");
    exit(125);
}
\$jxArgs = array_slice(\$argv, 1);
\$jxCommand = array_merge([\$jxPhp, \$jxSourcePath], \$jxArgs);
\$jxDescriptor = [
    0 => STDIN,
    1 => STDOUT,
    2 => STDERR,
];
\$jxProcess = proc_open(\$jxCommand, \$jxDescriptor, \$jxPipes);
if (!is_resource(\$jxProcess)) {
    @unlink(\$jxSourcePath);
    fwrite(STDERR, "JX: could not start PHP runtime for {\$jxSourceName}\n");
    exit(126);
}
\$jxExit = proc_close(\$jxProcess);
@unlink(\$jxSourcePath);
exit(\$jxExit);
PHP;
    }

    private function assertPhpSource(string $source, string $input): void
    {
        if (!str_contains($source, '<?php') && !str_starts_with(ltrim($source), '#!')) {
            throw new \RuntimeException("input does not look like PHP source: {$input}");
        }
    }

    private function parseCompileArgs(array $args): array
    {
        $input = null;
        $output = null;

        for ($i = 0; $i < count($args); $i++) {
            $arg = $args[$i];
            if ($arg === '-o' || $arg === '--output') {
                $output = $args[$i + 1] ?? null;
                $i++;
                continue;
            }
            if ($input === null) {
                $input = $arg;
            }
        }

        return [$input, $output];
    }

    private function exec(array $command): int
    {
        $process = proc_open($command, [0 => STDIN, 1 => STDOUT, 2 => STDERR], $pipes);
        if (!is_resource($process)) {
            return $this->fail("could not start executable\n");
        }

        return proc_close($process);
    }

    private function help(): int
    {
        fwrite(STDOUT, <<<TXT
JX - PHP to executable-code compiler layer

Commands:
  ./jx compile input.php -o build/app
  ./jx run input.php -- arg1 arg2

TXT);
        return 0;
    }

    private function fail(string $message): int
    {
        fwrite(STDERR, "JX: {$message}");
        return 1;
    }
}
